// <auto-generated />
namespace IndividualProjectRev3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class INIT4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INIT4));
        
        string IMigrationMetadata.Id
        {
            get { return "201811022205487_INIT4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
